query-dockerhub add input handling to ppa query

diff --git a/.github/workflows/fetch-mythbuntu-ppa.yml b/.github/workflows/fetch-mythbuntu-ppa.yml
--- a/.github/workflows/fetch-mythbuntu-ppa.yml
+++ b/.github/workflows/fetch-mythbuntu-ppa.yml
@@ -5,12 +5,22 @@ name: fetch-mythbuntu-ppa
 on:
   workflow_call:
     inputs:
-      ppa:
+      mythbuntu-release:
         description: 'mythbuntu PPA name'
         required: true
         type: string
-      depth:
-        description: 'number of build records fetched'
+      mythbuntu-arch:
+        description: 'arhitecture of interest'
+        required: false
+        type: string
+        default: 'amd64'
+      os-release:
+        description: 'OS version of interest'
+        required: false
+        type: string
+        default: '20.04'
+      record-count:
+        description: 'number of build records to fetch'
         required: false
         type: number
         default: 40
@@ -24,13 +34,19 @@ jobs:
     runs-on: ubuntu-latest
     outputs:
       info: ${{ steps.fetch-ppa-versions.outputs.versions }}
+    env:
+      mythbuntu-release: ${{ inputs.mythbuntu-release }}
+      record-count: ${{ inputs.record-count }}
+      mythbuntu-arch: ${{ inputs.mythbuntu-arch }}
+      os-release: ${{ inputs.os-release }}
     steps:
       - run: python -m pip install --upgrade pip
       - run: python -m pip install launchpadlib
       - id: fetch-ppa-versions
         run: |
-          versions=$(python -c '
+          result=$(python -c '
           import launchpadlib
+          import os
           import re
 
           from launchpadlib.launchpad import Launchpad
@@ -49,18 +65,29 @@ jobs:
               build.os = match.group("os")
             return build
 
+          ppa_name = os.environ["mythbuntu-release"]
+          records = os.environ["record-count"]
+          arch = os.environ["mythbuntu-arch"]
+          release = os.environ["os-release"]
+
           try:
             launchpad = Launchpad.login_anonymously("mythbuntu-ppa-query", "production", version="devel")
             mythbuntu = launchpad.people["mythbuntu"]
-            ppa = mythbuntu.getPPAByName(name="32")
-            all_records = ppa.getBuildRecords(build_state = "Successfully built")[:40]
-            amd64_records = (record for record in all_records if "amd64" == record.arch_tag)
-            amd64_builds = (tokenize_record(record) for record in amd64_records)
-            versions = (build.version for build in amd64_builds if "20.04" == build.os)
+            ppa = mythbuntu.getPPAByName(name=ppa_name)
+            all_records = ppa.getBuildRecords(build_state = "Successfully built")[:records]
+            arch_records = (record for record in all_records if record.arch_tag == arch)
+            arch_builds = (tokenize_record(record) for record in arch_records)
+            versions = (build.version for build in arch_builds if build.os == release)
             print(list(versions))
 
           except HTTPError as e:
             print(e.content)
+            sys.exit(1)
           ')
-          echo "::set-output name=versions::${versions//\'/\"}"
-          
+          if [[ $? -eq 0 ]]; then
+          echo "::set-output name=versions::${result//\'/\"}"
+          else
+          echo "::set-output name=versions::[]"
+          echo "::error file=fetch-mythbuntu-ppa.yml,line=83::${result}"
+          fi
+
